export const KAIZEN_STATUSES = [
  "DRAFT",
  "SUBMITTED",
  "UNDER_REVIEW",
  "NEEDS_CHANGES",
  "REJECTED",
  "APPROVED",
  "IMPLEMENTATION_IN_PROGRESS",
  "IMPLEMENTATION_COMPLETED",
  "BUSINESS_IMPACT_RECORDED",
  "REWARD_ISSUED",
  "ARCHIVED",
  "PUBLISHED_TO_KNOWLEDGE_BASE",
] as const;

export type KaizenStatus = (typeof KAIZEN_STATUSES)[number];
