export const ROUTES = {
  HOME: "/",
  SIGN_IN: "/sign-in",
  SIGN_UP: "/sign-up",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  ANALYTICS: "/dashboard/analytics",
  REPORTS: "/reports",
  REPORTS_HISTORY: "/reports/history",
  REPORTS_SCHEDULES: "/reports/schedules",
  REPORTS_TEMPLATES: "/reports/templates",
  MY_IDEAS: "/kaizen",
  NEW_KAIZEN: "/kaizen/new",
  REVIEW: "/review",
  IMPLEMENTATION: "/implementation",
  LEADERBOARD: "/leaderboard",
  NOTIFICATIONS: "/notifications",
  ADMIN: "/admin",
  MANAGER_DASHBOARD: "/manager/dashboard",
  HR_DASHBOARD: "/hr/dashboard",
  CMD_DASHBOARD: "/cmd/dashboard",
  ADMIN_DASHBOARD: "/admin/dashboard",
} as const;
