"use client";

import { useState } from "react";
import { useSearchParams } from "next/navigation";
import { Download, FileBarChart, Trash2 } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/feedback/empty-state";
import { ErrorState } from "@/components/feedback/error-state";
import { LoadingSkeleton } from "@/components/feedback/loading-skeleton";
import { toast } from "@/components/feedback/success-toast";
import { MyIdeasPagination } from "@/features/kaizen/components/my-ideas/my-ideas-pagination";
import { REPORT_TYPE_LABEL } from "@/features/reports/constants/report-types";
import { useDeleteExport, useDownloadExport, useReportExports } from "@/features/reports/hooks/use-report-exports";
import type { ExportStatus } from "@/features/reports/types/report-export";
import { ApiError } from "@/lib/api-client";
import { cn } from "@/lib/utils";
import { formatDate } from "@/utils/format";

const PAGE_SIZE = 15;

const STATUS_VARIANT: Record<ExportStatus, "secondary" | "info" | "success" | "destructive"> = {
  PENDING: "secondary",
  PROCESSING: "info",
  COMPLETED: "success",
  FAILED: "destructive",
};

function formatBytes(bytes: number | null): string {
  if (bytes === null) return "—";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

/** Report Download Center (Part 5) — "Generated reports, Generated by, Date, Report type,
 * Status, Size, Download, Delete." Distinct from Chunk 3A's in-page "Report History" (which logs
 * every Preview generation, never a file); this lists real `ReportExport` files. Polls while any
 * row is still PENDING/PROCESSING (`useReportExports`) so Status/Size update live without a
 * manual refresh. */
export function ReportDownloadCenter() {
  const [page, setPage] = useState(1);
  const searchParams = useSearchParams();
  const highlightId = searchParams.get("highlight");

  const query = useReportExports({ page, pageSize: PAGE_SIZE });
  const download = useDownloadExport();
  const remove = useDeleteExport();

  function handleDownload(id: string, fileName: string) {
    download.mutate(
      { id, fileName },
      { onError: (error) => toast.error(error instanceof ApiError ? error.message : "Could not download this export.") },
    );
  }

  function handleDelete(id: string) {
    if (!window.confirm("Delete this export? This cannot be undone.")) return;
    remove.mutate(id, {
      onSuccess: () => toast.success("Export deleted."),
      onError: (error) => toast.error(error instanceof ApiError ? error.message : "Could not delete this export."),
    });
  }

  if (query.isError) {
    const message = query.error instanceof ApiError ? query.error.message : "Something went wrong loading exports.";
    return <ErrorState title="Couldn't load the Download Center" description={message} onRetry={() => query.refetch()} />;
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col gap-1">
        <h1 className="text-2xl font-bold tracking-tight">Download Center</h1>
        <p className="text-muted-foreground text-sm">Every PDF, Excel, and CSV report you&apos;ve exported.</p>
      </div>

      {query.isLoading || !query.data ? (
        <div className="flex flex-col gap-2">
          {[...Array(5)].map((_, index) => (
            <LoadingSkeleton key={index} className="h-16 w-full rounded-lg" />
          ))}
        </div>
      ) : query.data.items.length === 0 ? (
        <EmptyState icon={FileBarChart} title="No exports yet" description="Export a report as PDF, Excel, or CSV to see it here." />
      ) : (
        <>
          <div className="flex flex-col gap-2">
            {query.data.items.map((item) => (
              <div
                key={item.id}
                className={cn(
                  "flex flex-col gap-2 rounded-lg border p-4 sm:flex-row sm:items-center sm:justify-between",
                  item.id === highlightId && "border-primary bg-primary/5",
                )}
              >
                <div className="flex flex-col gap-1">
                  <div className="flex items-center gap-2">
                    <p className="font-medium">{REPORT_TYPE_LABEL[item.reportType]}</p>
                    <Badge variant="outline">{item.format}</Badge>
                    <Badge variant={STATUS_VARIANT[item.status]}>{item.status}</Badge>
                  </div>
                  <p className="text-muted-foreground text-xs">
                    {item.generatedBy.displayName} · {formatDate(item.createdAt)} · {formatBytes(item.fileSizeBytes)}
                  </p>
                  {item.status === "FAILED" && item.errorMessage ? (
                    <p className="text-destructive text-xs">{item.errorMessage}</p>
                  ) : null}
                </div>
                <div className="flex items-center gap-2 self-end sm:self-auto">
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={item.status !== "COMPLETED" || download.isPending}
                    onClick={() => handleDownload(item.id, item.fileName)}
                  >
                    <Download className="h-4 w-4" />
                    Download
                  </Button>
                  <Button variant="ghost" size="sm" onClick={() => handleDelete(item.id)} disabled={remove.isPending}>
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            ))}
          </div>
          <MyIdeasPagination meta={query.data.meta} onPageChange={setPage} />
        </>
      )}
    </div>
  );
}
